### ISSUE TITLE
npm run dev is caught in deprecated packages

### ISSUE THREAD

**Issue by zwoefler** [ospic/webapp#1132]
**Describe the bug**
Running into deprecated packages and execution errors.

A few errors:
- node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
- node:internal/crypto/hash:67 this[kHandle] = new _Hash(algorithm, xofLen);
- details.family.toLowerCase is not a function

**To Reproduce**
1. nvm install --lts
2. npm install @vue/cli
3. Do steps in README
4. Run into errors when running `npm install`
5. Run into errors when executing `npm run dev`

**Expected behavior**
Install node/npm and vuejs as described in the README and run npm run dev to develop/test the application

**Wishing for**
Maybe provide a Docker-Image, or pin the required package versions in a script.

**Comment by elirehema** [comment]
@zwoefler can you attach your the screenshot ?

**Comment by elirehema** [comment]
Closed as no response
